apiVersion: v1
kind: Service
metadata:
  labels: {{- include "demo-chart.labels" . | nindent 2 -}}
  name: {{ .Values.container.name}}
spec:
  type: {{ .Values.spec.type}}
  selector:
    {{- include "demo-chart.selectorLabels" . | nindent 4 -}}
  ports:
    - port: {{ .Values.container.port}}
      targetPort: {{ .Values.container.port}}
      nodePort: {{ .Values.ports.nodePort}}
